"""workflow runtime: instances, tokens, task_results, decisions

Revision ID: 0019_workflow_runtime
Revises: 0018_workflow_graph_index
Create Date: 2026-08-30

Roadmap E05-05. An instance may only start on a PUBLISHED template version
(BEFORE INSERT trigger). Reversible.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0019_workflow_runtime"
down_revision: str | None = "0018_workflow_graph_index"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_instances",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("template_version_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="running", nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'cancelled', 'failed')",
            name=op.f("ck_workflow_instances_status"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_workflow_instances_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_version_id"],
            ["workflow_template_versions.id"],
            name=op.f("fk_workflow_instances_template_version_id_workflow_template_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_instances")),
    )
    op.create_index(
        op.f("ix_workflow_instances_event_id"), "workflow_instances", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_instances_status"), "workflow_instances", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_instances_template_version_id"),
        "workflow_instances",
        ["template_version_id"],
        unique=False,
    )
    op.create_table(
        "workflow_decisions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("connector_node_key", sa.String(length=64), nullable=False),
        sa.Column("chosen_branches", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("auto", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
            name=op.f("fk_workflow_decisions_decided_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["workflow_instances.id"],
            name=op.f("fk_workflow_decisions_instance_id_workflow_instances"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_decisions")),
    )
    op.create_index(
        op.f("ix_workflow_decisions_connector_node_key"),
        "workflow_decisions",
        ["connector_node_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_decisions_instance_id"),
        "workflow_decisions",
        ["instance_id"],
        unique=False,
    )
    op.create_table(
        "workflow_task_results",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("node_key", sa.String(length=64), nullable=False),
        sa.Column(
            "result",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("completed_by", sa.Uuid(), nullable=True),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["completed_by"],
            ["users.id"],
            name=op.f("fk_workflow_task_results_completed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["workflow_instances.id"],
            name=op.f("fk_workflow_task_results_instance_id_workflow_instances"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_task_results")),
    )
    op.create_index(
        op.f("ix_workflow_task_results_instance_id"),
        "workflow_task_results",
        ["instance_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_task_results_node_key"),
        "workflow_task_results",
        ["node_key"],
        unique=False,
    )
    op.create_table(
        "workflow_tokens",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("node_key", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), server_default="active", nullable=False),
        sa.Column(
            "entered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('active', 'waiting', 'consumed')", name=op.f("ck_workflow_tokens_state")
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["workflow_instances.id"],
            name=op.f("fk_workflow_tokens_instance_id_workflow_instances"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_tokens")),
    )
    op.create_index(
        op.f("ix_workflow_tokens_instance_id"), "workflow_tokens", ["instance_id"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_tokens_node_key"), "workflow_tokens", ["node_key"], unique=False
    )
    op.execute(
        "CREATE OR REPLACE FUNCTION bbz_forbid_instance_on_unpublished_version() "
        "RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE lc text; BEGIN "
        "SELECT lifecycle INTO lc FROM workflow_template_versions "
        "WHERE id = NEW.template_version_id; "
        "IF lc IS DISTINCT FROM 'published' THEN RAISE EXCEPTION "
        "'workflow_instances: template_version_id must reference a published version'; "
        "END IF; RETURN NEW; END; $$"
    )
    op.execute(
        "CREATE TRIGGER workflow_instances_published_version BEFORE INSERT "
        "ON workflow_instances FOR EACH ROW "
        "EXECUTE FUNCTION bbz_forbid_instance_on_unpublished_version()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflow_tokens_node_key"), table_name="workflow_tokens")
    op.drop_index(op.f("ix_workflow_tokens_instance_id"), table_name="workflow_tokens")
    op.drop_table("workflow_tokens")
    op.drop_index(op.f("ix_workflow_task_results_node_key"), table_name="workflow_task_results")
    op.drop_index(op.f("ix_workflow_task_results_instance_id"), table_name="workflow_task_results")
    op.drop_table("workflow_task_results")
    op.drop_index(op.f("ix_workflow_decisions_instance_id"), table_name="workflow_decisions")
    op.drop_index(op.f("ix_workflow_decisions_connector_node_key"), table_name="workflow_decisions")
    op.drop_table("workflow_decisions")
    op.execute("DROP TRIGGER IF EXISTS workflow_instances_published_version ON workflow_instances")
    op.execute("DROP FUNCTION IF EXISTS bbz_forbid_instance_on_unpublished_version()")
    op.drop_index(
        op.f("ix_workflow_instances_template_version_id"), table_name="workflow_instances"
    )
    op.drop_index(op.f("ix_workflow_instances_status"), table_name="workflow_instances")
    op.drop_index(op.f("ix_workflow_instances_event_id"), table_name="workflow_instances")
    op.drop_table("workflow_instances")
    # ### end Alembic commands ###
