"""audit_events.seq + audit_chain_links (hash chain)

Revision ID: 0053_audit_hash_chain
Revises: 0052_rate_limits
Create Date: 2026-09-02

Roadmap E23-09 / MASTER_PROMPT §17, extends E04-10. Adds a monotonic ``seq`` to
``audit_events`` (insertion order for the chain) and an append-only
``audit_chain_links`` table: one link per audit row, ``row_hash`` chained to the
previous link's hash. A leader-elected worker seals new rows and verifies the
chain; a break raises ``AUDIT_INTEGRITY_ALERT``. Additive / expand-only.

expand-contract: safe
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0053_audit_hash_chain"
down_revision: str | None = "0052_rate_limits"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TS = sa.DateTime(timezone=True)
_FN = "bbz_forbid_row_mutation"  # created by 0016


def upgrade() -> None:
    op.execute("ALTER TABLE audit_events ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY")
    op.create_index("ix_audit_events_seq", "audit_events", ["seq"], unique=True)

    op.create_table(
        "audit_chain_links",
        # seq mirrors audit_events.seq — set explicitly by the sealer, never auto.
        sa.Column("seq", sa.BigInteger(), primary_key=True, autoincrement=False, nullable=False),
        sa.Column("audit_event_id", sa.Uuid(), nullable=False),
        sa.Column("prev_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("row_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("sealed_at", _TS, nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_audit_chain_links_row_hash", "audit_chain_links", ["row_hash"])
    op.execute(
        "CREATE TRIGGER audit_chain_links_append_only BEFORE UPDATE OR DELETE "
        f"ON audit_chain_links FOR EACH ROW EXECUTE FUNCTION {_FN}()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_chain_links_append_only ON audit_chain_links")
    op.drop_index("ix_audit_chain_links_row_hash", table_name="audit_chain_links")
    op.drop_table("audit_chain_links")
    op.drop_index("ix_audit_events_seq", table_name="audit_events")
    op.execute("ALTER TABLE audit_events DROP COLUMN seq")
