"""Audit action vocabulary. Extended by later epics (events, calls, RBAC, ...)."""

from __future__ import annotations

import enum


class AuditAction(enum.StrEnum):
    LOGIN_SUCCEEDED = "LOGIN_SUCCEEDED"
    LOGIN_FAILED = "LOGIN_FAILED"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    SESSION_STARTED = "SESSION_STARTED"
    SESSION_ENDED = "SESSION_ENDED"
    MFA_ENROLLED = "MFA_ENROLLED"
    MFA_DISABLED = "MFA_DISABLED"
    MFA_CHALLENGE_FAILED = "MFA_CHALLENGE_FAILED"
    MFA_RECOVERY_USED = "MFA_RECOVERY_USED"
    EVENT_ASSIGNED = "EVENT_ASSIGNED"
    EVENT_TAKEN_OVER = "EVENT_TAKEN_OVER"
    EVENT_ARCHIVED = "EVENT_ARCHIVED"
    EVENT_REACTIVATED = "EVENT_REACTIVATED"
    EVENT_EXPORTED = "EVENT_EXPORTED"
    EXTERNAL_ACTION_DISPATCHED = "EXTERNAL_ACTION_DISPATCHED"
    EXTERNAL_ACTION_FAILED = "EXTERNAL_ACTION_FAILED"
    WORKER_LEADER_CHANGED = "WORKER_LEADER_CHANGED"
    WORKFLOW_TEMPLATE_VALIDATED = "WORKFLOW_TEMPLATE_VALIDATED"
    WORKFLOW_TEMPLATE_PUBLISHED = "WORKFLOW_TEMPLATE_PUBLISHED"
    WORKFLOW_TEMPLATE_DEPRECATED = "WORKFLOW_TEMPLATE_DEPRECATED"
    ACTION_STEP_COMPLETED = "ACTION_STEP_COMPLETED"
    WORKFLOW_DECISION_MADE = "WORKFLOW_DECISION_MADE"


#: Actions that MUST be emitted from a write path (MASTER_PROMPT §17). A missing
#: wiring is caught by the "critical action -> audit" contract test (E04-03).
CRITICAL_ACTIONS: frozenset[AuditAction] = frozenset(
    {
        AuditAction.EVENT_ASSIGNED,
        AuditAction.EVENT_TAKEN_OVER,
        AuditAction.EVENT_ARCHIVED,
        AuditAction.EVENT_REACTIVATED,
        AuditAction.EVENT_EXPORTED,
        AuditAction.EXTERNAL_ACTION_DISPATCHED,
        AuditAction.EXTERNAL_ACTION_FAILED,
        AuditAction.WORKFLOW_TEMPLATE_VALIDATED,
        AuditAction.WORKFLOW_TEMPLATE_PUBLISHED,
        AuditAction.WORKFLOW_TEMPLATE_DEPRECATED,
        AuditAction.ACTION_STEP_COMPLETED,
        AuditAction.WORKFLOW_DECISION_MADE,
    }
)
