"""Audit action vocabulary. Extended by later epics (events, calls, RBAC, ...)."""

from __future__ import annotations

import enum


class AuditAction(enum.StrEnum):
    LOGIN_SUCCEEDED = "LOGIN_SUCCEEDED"
    LOGIN_FAILED = "LOGIN_FAILED"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    SESSION_STARTED = "SESSION_STARTED"
    SESSION_ENDED = "SESSION_ENDED"
    MFA_ENROLLED = "MFA_ENROLLED"
    MFA_DISABLED = "MFA_DISABLED"
    MFA_CHALLENGE_FAILED = "MFA_CHALLENGE_FAILED"
    MFA_RECOVERY_USED = "MFA_RECOVERY_USED"
    AUTH_MAPPING_CHANGED = "AUTH_MAPPING_CHANGED"
    USER_ROLE_ASSIGNED = "USER_ROLE_ASSIGNED"
    USER_ROLE_REVOKED = "USER_ROLE_REVOKED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    DIRECTORY_SYNC_COMPLETED = "DIRECTORY_SYNC_COMPLETED"
    MFA_POLICY_CHANGED = "MFA_POLICY_CHANGED"
    MFA_STEPUP_REQUIRED = "MFA_STEPUP_REQUIRED"
    WEBAUTHN_REGISTERED = "WEBAUTHN_REGISTERED"
    WEBAUTHN_REMOVED = "WEBAUTHN_REMOVED"
    PERMISSION_DELEGATED = "PERMISSION_DELEGATED"
    PERMISSION_DELEGATION_REVOKED = "PERMISSION_DELEGATION_REVOKED"
    IDENTITY_LINKED = "IDENTITY_LINKED"
    IDENTITY_UNLINKED = "IDENTITY_UNLINKED"
    AUTH_PROVIDER_CONFIGURED = "AUTH_PROVIDER_CONFIGURED"
    EVENT_ASSIGNED = "EVENT_ASSIGNED"
    EVENT_TAKEN_OVER = "EVENT_TAKEN_OVER"
    EVENT_ARCHIVED = "EVENT_ARCHIVED"
    EVENT_REACTIVATED = "EVENT_REACTIVATED"
    EVENT_EXPORTED = "EVENT_EXPORTED"
    EVENT_NOTE_ADDED = "EVENT_NOTE_ADDED"
    EVENT_NOTE_UPDATED = "EVENT_NOTE_UPDATED"
    EXTERNAL_ACTION_DISPATCHED = "EXTERNAL_ACTION_DISPATCHED"
    EXTERNAL_ACTION_FAILED = "EXTERNAL_ACTION_FAILED"
    WORKER_LEADER_CHANGED = "WORKER_LEADER_CHANGED"
    WORKFLOW_TEMPLATE_VALIDATED = "WORKFLOW_TEMPLATE_VALIDATED"
    WORKFLOW_TEMPLATE_PUBLISHED = "WORKFLOW_TEMPLATE_PUBLISHED"
    WORKFLOW_TEMPLATE_DEPRECATED = "WORKFLOW_TEMPLATE_DEPRECATED"
    ACTION_STEP_COMPLETED = "ACTION_STEP_COMPLETED"
    WORKFLOW_DECISION_MADE = "WORKFLOW_DECISION_MADE"
    WORKFLOW_INSTANCE_STARTED = "WORKFLOW_INSTANCE_STARTED"
    WORKFLOW_TEMPLATE_CREATED = "WORKFLOW_TEMPLATE_CREATED"
    WORKFLOW_TEMPLATE_UPDATED = "WORKFLOW_TEMPLATE_UPDATED"
    WORKFLOW_SIMULATED = "WORKFLOW_SIMULATED"
    #: leader-key change observed by the cluster watcher (emitter: E06-04 / #85).
    DB_FAILOVER = "DB_FAILOVER"
    ROLLING_UPDATE_STARTED = "ROLLING_UPDATE_STARTED"
    ROLLING_UPDATE_COMPLETED = "ROLLING_UPDATE_COMPLETED"
    BACKUP_COMPLETED = "BACKUP_COMPLETED"
    RESTORE_PERFORMED = "RESTORE_PERFORMED"
    CALL_RINGING = "CALL_RINGING"
    CALL_ANSWERED = "CALL_ANSWERED"
    CALL_ENDED = "CALL_ENDED"
    CALL_CONTROL_ACTION = "CALL_CONTROL_ACTION"
    CALL_DOCUMENTED = "CALL_DOCUMENTED"
    CONTACT_CREATED = "CONTACT_CREATED"
    CONTACT_UPDATED = "CONTACT_UPDATED"
    CONTACT_DELETED = "CONTACT_DELETED"
    CONTACT_PRIORITY_CHANGED = "CONTACT_PRIORITY_CHANGED"
    TRIGGER_EXECUTED = "TRIGGER_EXECUTED"
    TECHNICAL_ENDPOINT_CREATED = "TECHNICAL_ENDPOINT_CREATED"
    TECHNICAL_ENDPOINT_UPDATED = "TECHNICAL_ENDPOINT_UPDATED"
    TECHNICAL_ENDPOINT_DELETED = "TECHNICAL_ENDPOINT_DELETED"
    TECHNICAL_ENDPOINT_MAPPED = "TECHNICAL_ENDPOINT_MAPPED"
    TRIGGER_RULE_CREATED = "TRIGGER_RULE_CREATED"
    TRIGGER_RULE_UPDATED = "TRIGGER_RULE_UPDATED"
    TRIGGER_RULE_VALIDATED = "TRIGGER_RULE_VALIDATED"
    TRIGGER_RULE_PUBLISHED = "TRIGGER_RULE_PUBLISHED"
    TRIGGER_RULE_RETIRED = "TRIGGER_RULE_RETIRED"
    TRIGGER_SIMULATED = "TRIGGER_SIMULATED"
    CLIENT_POPUP_DELIVERED = "CLIENT_POPUP_DELIVERED"
    CODA_ALARM_SOURCE_CONFIGURED = "CODA_ALARM_SOURCE_CONFIGURED"
    CODA_ALARM_SOURCE_REMOVED = "CODA_ALARM_SOURCE_REMOVED"
    DOOR_PROFILE_CREATED = "DOOR_PROFILE_CREATED"
    DOOR_PROFILE_UPDATED = "DOOR_PROFILE_UPDATED"
    DOOR_PROFILE_DELETED = "DOOR_PROFILE_DELETED"
    DOOR_OPEN_REQUESTED = "DOOR_OPEN_REQUESTED"
    DOOR_OPEN_RESULT = "DOOR_OPEN_RESULT"
    WEATHER_EVENT_CREATED = "WEATHER_EVENT_CREATED"
    MONITOR_ROUTE_CHANGED = "MONITOR_ROUTE_CHANGED"
    MONITOR_PROFILE_APPLIED = "MONITOR_PROFILE_APPLIED"


#: Actions that MUST be emitted from a write path (MASTER_PROMPT §17). A missing
#: wiring is caught by the "critical action -> audit" contract test (E04-03).
CRITICAL_ACTIONS: frozenset[AuditAction] = frozenset(
    {
        AuditAction.AUTH_MAPPING_CHANGED,
        AuditAction.USER_DEACTIVATED,
        AuditAction.DIRECTORY_SYNC_COMPLETED,
        AuditAction.MFA_POLICY_CHANGED,
        AuditAction.MFA_STEPUP_REQUIRED,
        AuditAction.PERMISSION_DELEGATED,
        AuditAction.PERMISSION_DELEGATION_REVOKED,
        AuditAction.IDENTITY_LINKED,
        AuditAction.IDENTITY_UNLINKED,
        AuditAction.AUTH_PROVIDER_CONFIGURED,
        AuditAction.EVENT_ASSIGNED,
        AuditAction.EVENT_TAKEN_OVER,
        AuditAction.EVENT_ARCHIVED,
        AuditAction.EVENT_REACTIVATED,
        AuditAction.EVENT_EXPORTED,
        AuditAction.EVENT_NOTE_ADDED,
        AuditAction.EVENT_NOTE_UPDATED,
        AuditAction.EXTERNAL_ACTION_DISPATCHED,
        AuditAction.EXTERNAL_ACTION_FAILED,
        AuditAction.WORKFLOW_TEMPLATE_VALIDATED,
        AuditAction.WORKFLOW_TEMPLATE_PUBLISHED,
        AuditAction.WORKFLOW_TEMPLATE_DEPRECATED,
        AuditAction.ACTION_STEP_COMPLETED,
        AuditAction.WORKFLOW_DECISION_MADE,
        AuditAction.WORKFLOW_INSTANCE_STARTED,
        AuditAction.WORKFLOW_TEMPLATE_CREATED,
        AuditAction.WORKFLOW_TEMPLATE_UPDATED,
        AuditAction.WORKFLOW_SIMULATED,
        AuditAction.ROLLING_UPDATE_STARTED,
        AuditAction.ROLLING_UPDATE_COMPLETED,
        AuditAction.BACKUP_COMPLETED,
        AuditAction.RESTORE_PERFORMED,
        AuditAction.CALL_RINGING,
        AuditAction.CALL_ANSWERED,
        AuditAction.CALL_ENDED,
        AuditAction.CALL_CONTROL_ACTION,
        AuditAction.CALL_DOCUMENTED,
        AuditAction.CONTACT_CREATED,
        AuditAction.CONTACT_UPDATED,
        AuditAction.CONTACT_DELETED,
        AuditAction.CONTACT_PRIORITY_CHANGED,
        AuditAction.TRIGGER_EXECUTED,
        AuditAction.TECHNICAL_ENDPOINT_CREATED,
        AuditAction.TECHNICAL_ENDPOINT_UPDATED,
        AuditAction.TECHNICAL_ENDPOINT_DELETED,
        AuditAction.TECHNICAL_ENDPOINT_MAPPED,
        AuditAction.TRIGGER_RULE_CREATED,
        AuditAction.TRIGGER_RULE_UPDATED,
        AuditAction.TRIGGER_RULE_VALIDATED,
        AuditAction.TRIGGER_RULE_PUBLISHED,
        AuditAction.TRIGGER_RULE_RETIRED,
        AuditAction.TRIGGER_SIMULATED,
        AuditAction.CLIENT_POPUP_DELIVERED,
        AuditAction.CODA_ALARM_SOURCE_CONFIGURED,
        AuditAction.CODA_ALARM_SOURCE_REMOVED,
        AuditAction.DOOR_PROFILE_CREATED,
        AuditAction.DOOR_PROFILE_UPDATED,
        AuditAction.DOOR_PROFILE_DELETED,
        AuditAction.DOOR_OPEN_REQUESTED,
        AuditAction.DOOR_OPEN_RESULT,
        AuditAction.WEATHER_EVENT_CREATED,
        AuditAction.MONITOR_ROUTE_CHANGED,
        AuditAction.MONITOR_PROFILE_APPLIED,
    }
)
